In [1]:
import tensorflow as tf
import numpy as np

In [2]:
n_inputs = 3
n_neurons = 5

In [7]:
X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0,Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0,Wy) + tf.matmul(X1,Wx) + b)

init = tf.global_variables_initializer()

In [8]:
# Mini-batch: instance 0,instance 1,instance 2,instance 3
X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]]) # t = 0
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]]) # t = 1

In [9]:
with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], {X0: X0_batch, X1: X1_batch})

In [10]:
Y0_val

array([[-0.9523195 , -0.85811615, -0.03412393,  0.98896158,  0.39534685],
       [-0.97428453, -0.99189174, -0.99991691,  0.99999785,  0.43916351],
       [-0.98620248, -0.99956602, -1.        ,  1.        ,  0.48098576],
       [ 1.        ,  0.99966574, -1.        , -0.99805707, -0.99999195]], dtype=float32)

In [11]:
Y1_val

array([[ 0.98291838, -0.95997286, -1.        ,  0.99999994,  0.22846414],
       [ 0.96999216, -0.6667279 ,  0.99630213, -0.98926681,  0.79817802],
       [ 0.99747491, -0.98321831, -0.99999744,  0.99712712,  0.68237472],
       [ 0.68170136, -0.99961853, -1.        ,  0.98440701, -0.83958638]], dtype=float32)

In [20]:
tf.reset_default_graph()

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seq, states = tf.contrib.rnn.static_rnn(basic_cell, [X0,X1], dtype=tf.float32)

Y0, Y1 = output_seq

init = tf.global_variables_initializer()

In [21]:
with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], {X0: X0_batch, X1: X1_batch})

In [22]:
Y0_val

array([[ 0.82928681,  0.38400865, -0.51206952,  0.295212  , -0.39787424],
       [ 0.98196048,  0.83321494, -0.99205148,  0.85779494, -0.69232309],
       [ 0.99822605,  0.96348423, -0.99990135,  0.97869432, -0.85746402],
       [-0.99673879,  0.6324116 , -0.99194813,  0.9481253 , -0.73192328]], dtype=float32)

In [23]:
Y1_val

array([[ 0.98600572,  0.98089683, -0.99999774,  0.9858821 , -0.78866124],
       [-0.09924302,  0.69884825, -0.80495238, -0.15745154, -0.00391487],
       [ 0.76091266,  0.97474551, -0.99991763,  0.90128875, -0.40916684],
       [-0.62760711,  0.95670551, -0.90570825,  0.90074688,  0.76461661]], dtype=float32)

In [25]:
n_steps = 2

In [28]:
tf.reset_default_graph()

seq_length = tf.placeholder(tf.int32, [None])
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32, sequence_length=seq_length)

init = tf.global_variables_initializer()

In [30]:
X_batch = np.array([
# step 0 step 1
    [[0, 1, 2], [9, 8, 7]], # instance 0
    [[3, 4, 5], [0, 0, 0]], # instance 1 (padded with a zero vector)
    [[6, 7, 8], [6, 5, 4]], # instance 2
    [[9, 0, 1], [3, 2, 1]], # instance 3
])

seq_length_batch = np.array([2,1,2,2])

In [33]:
with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: X_batch, seq_length: seq_length_batch})

In [34]:
states_val

array([[-0.14383519,  0.99996406, -0.95830286, -0.99992007,  0.99985737],
       [-0.1661095 ,  0.99846476,  0.18498679, -0.94159162,  0.94259858],
       [ 0.26813069,  0.99922878, -0.93374765, -0.99744654,  0.99290204],
       [ 0.65809703,  0.87931794, -0.92995095, -0.81421828,  0.81147599]], dtype=float32)